name: 🚀 Deploy to AlwaysData
on:
 push:
  branches:
   - main
jobs:
 deploy:
  runs-on: ubuntu-latest
  steps:
   - name: 📦 Clonar repositorio
     uses: actions/checkout@v4
     
   - name: 🚀 Subir archivos al hosting vía FTPS (AlwaysData)
     uses: SamKirkland/FTP-Deploy-Action@v4.3.5
     with:
      server: ${{ secrets.FTP_SERVER }}
      username: ${{ secrets.FTP_USERNAME }}
      password: ${{ secrets.FTP_PASSWORD }}
      server-dir: ${{ secrets.FTP_TARGET }}/
      port: 21
      protocol: ftps
      security: strict    
      local-dir: ./
      exclude: |
       **/.git*
       **/.github*
       **/README.md
       **/node_modules/**
       **/.env
